skillMetadata:
    sections:
        - name: Calendars to Enable
          fields:
            - type: label
              label: List the names of all calendars you would like to have checked, separated by commas. For example, if you have two calendars named Business and Personal, you would input to the field "Business, Personal". If both fields are left blank, only the primary calendar will be read. This field is case sensitive.
            - name: enabled_calendar_list
              type: text
              label: Enabled Calendars
              value: ""
            - name: enable_all_calendars
              type: checkbox
              label: Enable all calendars (overrides above field)
              value: "false"
            - type: label
              label: Enabling all calendars will slow down the processing if you have a large number of calendars.
        - name: 24-Hour Clock
          fields:
            - name: en_24h_clock
              type: checkbox
              label: Enable 24-hour clock
              value: "true"
